### ISSUE TITLE
Get PNG from online PDF

### ISSUE THREAD

**Issue by saelco** [miguelpruivo/flutter_pdf_previewer#1]
I want to get PNG from online PDF without download the pdf. How to do that?

**Comment by miguelpruivo** [comment]
How are you suppose to get the preview of the PDF without downloading it? Somehow, you'll have to always do it.

**Comment by miguelpruivo** [comment]
Closing as this actually doesn't represent an issue. Feel free to reopen if you have any suggestion.

Thank you.
